### ISSUE TITLE
حداقل به پرداخت را میزدی

### ISSUE THREAD

**Issue by vahidalvandi** [dena-a/iran-payment#14]
سلام کدنویسی عالی
ولی حداقل به پرداخت را بزن

**Comment by dena-a** [comment]
با توجه به شرایط دریافت اطلاعات و اتصال به وب سرویس‌های بانکی فقط بعد از عقد قرارداد امکان پذیر هست.
به همین دلیل امکان پیاده سازی تمامی درگاه‌ها وجود ندارد.
