### ISSUE TITLE
خطای Call to undefined method Dena\IranPayment\Gateways\Saman\Saman::setUserId()

### ISSUE THREAD

**Issue by croner2** [dena-a/iran-payment#24]
با سلام
من پکیج را نصب کردم ولی متاسفانه در صفحه پرداخت خطای 
Call to undefined method Dena\IranPayment\Gateways\Saman\Saman::setUserId()

رو می دهد دلیل چیست؟

**Comment by dena-a** [comment]
سلام
امکان استنفاده از کلاس Saman به صورت تنها وجود ندارد. برای این کار میتونی از کد زیر استفاده کنی:
```
$payment = IranPayment::create('saman');

$payment->setUserId($user->id)
        ->setAmount($data['amount'])
        ->setCallbackUrl(route('bank.callback'))
        ->ready();

return $payment->redirect();
```
